jobs:
  - name: mohit-1
    type: manifest
    steps:
      - IN: box-nginx-1
      - IN: trigger-dv-man

  - name: mohit-2
    type: manifest
    steps:
      - IN: box-sn-1
      - IN: trigger-dv-man
  

  # - name: ecs-deploy
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: tri-deploy-1
    type: deploy
    steps:
      - IN: mohit-1
      - IN: tri-cluster-1
      - IN: mohit-2
      - TASK: managed
        deployMethod: upgrade

  # - name: tri-deploy-2
  #   type: tripubDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: gkeDeploy
  #   type: deploy
  #   steps:
  #     - IN: jatin-1
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - IN: box-man-1
  #     - IN: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
