jobs:
  - name: mohit-1
    type: manifest
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man

  - name: mohit-2
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man
  

  - name: ecs-deploy-mohit
    type: deploy
    on_start:
      - NOTIFY: slackNotification
    on_success:
      - NOTIFY: slackNotification
    on_failure:
      - NOTIFY: myEmail
    steps:
      - IN: mohit-2
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: tri-deploy-1
    type: deploy
    on_start:
      - NOTIFY: slackNotification
    on_success:
      - NOTIFY: slackNotification
    steps:
      - IN: mohit-1
      - IN: tri-cluster
      - TASK: managed
        deployMethod: upgrade

  # - name: tri-deploy-2
  #   type: tripubDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: gkeDeploy
  #   type: deploy
  #   steps:
  #     - IN: jatin-1
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: ddc-deploy
    type: deploy
    on_start:
      - NOTIFY: myEmail
    on_success:
      - NOTIFY: myEmail
    on_failure:
      - NOTIFY: myEmail
    steps:
      #- IN: box-man-1
      - IN: ddc-cluster
      - IN: mohit-2

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
