jobs:
  # - name: sh-manifestjob2
  #   type: manifest
  #   steps:
  #     - IN: sh-myapp2
  #     - IN: sh-docker-opts
  #     - IN: sh-trigger
  #     #- IN: dv-params

  #     #- IN: sh-lb-1

  - name: sn-file-man-16
    type: manifest
    steps:
      - IN: sn-file
      - IN: sh-trigger
      # - IN: sn-file-2
      # - IN: my-params
        # applyTo:
        #   - sn-file
      # - IN: my-params-2
      #   applyTo:
      #     - sn-file-2

  # - name: sn-vici-man
  #   type: manifest
  #   steps:
  #     - IN: sn-vici-http-js
  #     - IN: sn-file-man
  #     - IN: sn-vici-trigger

  # - name: sn-cluster-dep-file
  #   type: deploy
  #   steps:
  #     - IN: sn-file-man-16
  #     - IN: sn-cluster-file
  #     - TASK:
  #        - script: echo "$HELLO"


  # - name: sn-cluster-dep-image
  #   type: deploy
  #   steps:
  #     - IN: sh-manifestjob1
  #     - IN: sn-cluster-image

  - name: build-mexec
    type: runSh
    steps:
      # - OUT: sn-file
      #- IN: microbase-img
      - IN: sh-trigger
      - TASK:
        - script: echo 'Hello'
      - OUT: sn-file
    on_success:
      - script: echo 'on success !!!!!'
      - script: echo 'uname is'
      - script: uname -a
      - script: echo 'hello'

  # - name: sh-ecsDeploy
  #   type: deploy
  #   steps:
  #     - IN: sh-manifestjob1
  #     - IN: sh-ecs-cluster
  #     - IN: sh-lb-2
  #       applyTo:
  #         - manifest: sh-manifestjob1 # it can only apply to one manifest
  #           image: sh-myapp3 # it can only apply to one image in the manifest
  #           port: 80
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: ddc-deploy1234
  #   type: deploy
  #   steps:
  #     - IN: ddccluster
  #     - IN: sh-manifestjob1

  # - name: deploytriton
  #   type: deploy
  #   steps:
  #     - IN: tri-cluster
  #     - IN: sh-manifestjob1
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: deployecs
  #   type: deploy
  #   steps:
  #     - IN: ecs-cluster
  #     - IN: sh-manifestjob1

  - name: deploygce2upgrade
    type: deploy
    steps:
      - IN: trip-cluster
      - IN: sn-file-man-16
      - TASK: managed
        deployMethod: upgrade

  # - name: deployddc
  #   type: deploy
  #   steps:
  #     - IN: ddc-cluster
  #     - IN: sh-manifestjob1



  # - name: stagingRelease
  #   type: release
  #   steps:
  #     #- IN: releaseTrigger
  #     - IN: stagingVerBase
  #       #switch: on
  #     - IN: sh-manifestjob1
  #     - TASK: managed
  #       bump: major

  # - name: tri-deploy123
  #   type: deploy
  #   steps:
  #     #- IN: sh-manifestjob1
  #    # - IN: version-resource
  #    # - IN: releaseTrigger
  #     #- IN: stagingVerBase
  #     - IN: stagingRelease
  #     - IN: tri-cluster
  #     # - TASK: managed
  #       # deployMethod: upgrade
  #       # bump: major

  # - name: sample
  #   type: runSh
  #   steps:
  #     - IN: sample_node
  #   on_success:
  #     - script: echo 'This block executes after TASK section executes successfully'

  # - name: release-job
  #   type: release
  #   steps:
  #     - IN: sample_node
  #   on_success:
  #     - script: echo 'This block executes after TASK section executes successfully'

  # - name: release-one
  #   type: release
  #   steps:
  #     - IN: version-resource
  #     - IN: sh-manifestjob1
  #     # - TASK: managed
  #     #   bump: major






        #switch: off
    # on_failure:
    #   - NOTIFY: stagingSlack

  # # - name: gke-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: scale
  #     - IN: gkecluster
  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: dcl-cluster

    # - name: jatin-2
  #   type: manifest
  #   steps:
  #     - GET: box-sn
  #     - GET: trigger-dv-man

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: jatin-1
  #     - GET: jatin-2
  #     - GET: ecs-cluster

  # - name: tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: box-man-1
  #     - GET: tri-cluster

  #- name: gkeDeploy
   # type: gkeDeploy
   # steps:
    #  - GET: jD-1
    #  - GET: gke-cluster
    #  - TASK: managed
    #    deployMethod: upgrade

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: ddc-cluster

  # - name: tri-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: manifestjob2
  #     - IN: tri-cluster
  #     # - TASK: managed
  #     #   deployMethod: upgrade
